services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-weather'
    environment:
      - 'POSTGRES_DB=postgres-weather'
      - 'POSTGRES_USER=${POSTGRES_USERNAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'
    volumes:
      - ~/weather:/var/lib/postgresql/data
    restart: unless-stopped